{
 "title": "Home Sensor",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   { "name": "bucket", "label": "Bucket", "query": { "query": "buckets()" } },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.client != \"\")\n  |> keep(columns: [\"client\"])\n  |> distinct(column: \"client\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r.sensor == \"bme280\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r.sensor == \"bme280\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> filter(fn: (r) => r.sensor == \"bme280\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "CO₂",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\n  |> filter(fn: (r) => r.sensor == \"mh-z19c\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r.sensor == \"bme280\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r.sensor == \"bme280\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> filter(fn: (r) => r.sensor == \"bme280\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\n  |> filter(fn: (r) => r.sensor == \"mh-z19c\")\n  |> filter(fn: (r) => r.client == \"${client}\")\n  |> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  }
 ]
}